source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ITDAvatarPlaceholder_Example' do
  pod 'ITDAvatarPlaceholder', :path => '../'
end

target 'ITDAvatarPlaceholder_Tests' do
  pod 'ITDAvatarPlaceholder', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
